<?php

//@UTF-8 defense_policy.php

  if (defined("_DEFENSE_POLICY_PHP_"))
    return;
  else 
  {
    /* _defense_POLICY_PHP_ routine */
    $_DEFENSE_POLICY['CONFIG']['ADMIN']['MODULE_NAME'] = "Q0FTVExFIC0gY2F1Z3M=";
    $_DEFENSE_POLICY['CONFIG']['ADMIN']['ID'] = "Y2F1Z3M=";
    $_DEFENSE_POLICY['CONFIG']['ADMIN']['PASSWORD'] = "NDMxY2NkNjA3ODNjZjk2NmI2NjBkZGQ3YjM0Njk2YTY=";
    $_DEFENSE_POLICY['CONFIG']['ADMIN']['LASTMODIFIED'] = "MTM5NTM4NTQ5MA==";
    $_DEFENSE_POLICY['CONFIG']['SITE']['BOOL'] = "VFJVRQ==";
    $_DEFENSE_POLICY['CONFIG']['MODE']['ENFORCING'] = "VFJVRQ==";
    $_DEFENSE_POLICY['CONFIG']['MODE']['PERMISSIVE'] = "RkFMU0U=";
    $_DEFENSE_POLICY['CONFIG']['MODE']['DISABLED'] = "RkFMU0U=";
    $_DEFENSE_POLICY['CONFIG']['ALERT']['ALERT'] = "VFJVRQ==";
    $_DEFENSE_POLICY['CONFIG']['ALERT']['MESSAGE'] = "RkFMU0U=";
    $_DEFENSE_POLICY['CONFIG']['ALERT']['STEALTH'] = "RkFMU0U=";
    $_DEFENSE_POLICY['CONFIG']['LOG']['BOOL'] = "VFJVRQ==";
    $_DEFENSE_POLICY['CONFIG']['LOG']['FILENAME'] = "Y19sb2cudHh0";
    $_DEFENSE_POLICY['CONFIG']['LOG']['DETAIL'] = "RkFMU0U=";
    $_DEFENSE_POLICY['CONFIG']['LOG']['SIMPLE'] = "VFJVRQ==";
    $_DEFENSE_POLICY['CONFIG']['LOG']['LIST_COUNT'] = "MTA=";
    $_DEFENSE_POLICY['CONFIG']['LOG']['CHARSET']['UTF-8'] = "VFJVRQ==";
    $_DEFENSE_POLICY['CONFIG']['LOG']['CHARSET']['eucKR'] = "RkFMU0U=";
    $_DEFENSE_POLICY['CONFIG']['TARGET']['GET'] = "VFJVRQ==";
    $_DEFENSE_POLICY['CONFIG']['TARGET']['POST'] = "VFJVRQ==";
    $_DEFENSE_POLICY['CONFIG']['TARGET']['FILE'] = "VFJVRQ==";
    $_DEFENSE_POLICY['CONFIG']['TARGET']['COOKIE'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['BOOL'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['0'] = "ZGVsZXRlW1s6c3BhY2U6XV0rZnJvbQ==";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['1'] = "ZHJvcFtbOnNwYWNlOl1dK2RhdGFiYXNl";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['2'] = "ZHJvcFtbOnNwYWNlOl1dK3RhYmxl";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['3'] = "ZHJvcFtbOnNwYWNlOl1dK2NvbHVtbg==";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['4'] = "ZHJvcFtbOnNwYWNlOl1dK3Byb2NlZHVyZQ==";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['5'] = "Y3JlYXRlW1s6c3BhY2U6XV0rdGFibGU=";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['6'] = "dXBkYXRlW1s6c3BhY2U6XV0rLipbWzpzcGFjZTpdXStzZXQ=";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['7'] = "aW5zZXJ0W1s6c3BhY2U6XV0raW50by4qW1s6c3BhY2U6XV0rdmFsdWVz";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['8'] = "c2VsZWN0W1s6c3BhY2U6XV0rLipbWzpzcGFjZTpdXStmcm9t";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['9'] = "YnVsa1tbOnNwYWNlOl1dK2luc2VydA==";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['10'] = "dW5pb25bWzpzcGFjZTpdXStzZWxlY3Q=";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['11'] = "b3IrW1s6c3BhY2U6XV0rW2EtekEtWl0rW1s6c3BhY2U6XV0qWydcIl0/W1s6c3BhY2U6XV0qPVtbOnNwYWNlOl1dKlwoP1snXCJdP1tbOnNwYWNlOl1dKlthLXpBLVpdKw==";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['12'] = "b3IrW1s6c3BhY2U6XV0rWzAtOV0rW1s6c3BhY2U6XV0qWydcIl0/W1s6c3BhY2U6XV0qPVtbOnNwYWNlOl1dKlwoP1snXCJdP1tbOnNwYWNlOl1dKlswLTldKw==";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['13'] = "YWx0ZXJbWzpzcGFjZTpdXSt0YWJsZQ==";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['14'] = "aW50b1tbOnNwYWNlOl1dK291dGZpbGU=";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['15'] = "bG9hZFtbOnNwYWNlOl1dK2RhdGE=";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['16'] = "ZGVjbGFyZS4rdmFyY2hhci4rc2V0";
    $_DEFENSE_POLICY['POLICY']['SQL_INJECTION']['LIST']['17'] = "YW5kK1tbOnNwYWNlOl1dK1swLTldK1snPSdd";
    $_DEFENSE_POLICY['POLICY']['XSS']['BOOL'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['0'] = "PHNjcmlwdA==";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['1'] = "JTNzY3JpcHQ=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['2'] = "A3NjcmlwdA==";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['3'] = "amF2YXNjcmlwdDo=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['4'] = "JTAw";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['5'] = "ZXhwcmVzc2lvbltbOnNwYWNlOl1dKlwoKlwp";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['6'] = "eHNzOipcKCpcKQ==";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['7'] = "ZG9jdW1lbnQuY29va2ll";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['8'] = "ZG9jdW1lbnQubG9jYXRpb24=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['9'] = "ZG9jdW1lbnQud3JpdGU=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['10'] = "b25BYm9ydFtbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['11'] = "b25CbHVyW1s6c3BhY2U6XV0qPQ==";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['12'] = "b25DaGFuZ2VbWzpzcGFjZTpdXSo9";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['13'] = "b25DbGlja1tbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['14'] = "b25EYmxDbGlja1tbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['15'] = "b25EcmFnRHJvcFtbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['16'] = "b25FcnJvcltbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['17'] = "b25Gb2N1c1tbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['18'] = "b25LZXlEb3duW1s6c3BhY2U6XV0qPQ==";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['19'] = "b25LZXlQcmVzc1tbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['20'] = "b25LZXlVcFtbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['21'] = "b25Mb2FkW1s6c3BhY2U6XV0qPQ==";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['22'] = "b25Nb3VzZURvd25bWzpzcGFjZTpdXSo9";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['23'] = "b25Nb3VzZU1vdmVbWzpzcGFjZTpdXSo9";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['24'] = "b25Nb3VzZU91dFtbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['25'] = "b25Nb3VzZU92ZXJbWzpzcGFjZTpdXSo9";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['26'] = "b25Nb3VzZVVwW1s6c3BhY2U6XV0qPQ==";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['27'] = "b25Nb3ZlW1s6c3BhY2U6XV0qPQ==";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['28'] = "b25SZXNldFtbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['29'] = "b25SZXNpemVbWzpzcGFjZTpdXSo9";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['30'] = "b25TZWxlY3RbWzpzcGFjZTpdXSo9";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['31'] = "b25TdWJtaXRbWzpzcGFjZTpdXSo9";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['32'] = "b25VbmxvYWRbWzpzcGFjZTpdXSo9";
    $_DEFENSE_POLICY['POLICY']['XSS']['LIST']['33'] = "bG9jYXRpb24uaHJlZltbOnNwYWNlOl1dKj0=";
    $_DEFENSE_POLICY['POLICY']['WORD']['BOOL'] = "RkFMU0U=";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['0'] = "7IOI64G8";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['1'] = "6rCc7IOI64G8";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['2'] = "7IaM7IOI64G8";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['3'] = "67OR7Iug";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['4'] = "7KeA656E";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['5'] = "7JSo7YyU";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['6'] = "7Iut7YyU";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['7'] = "64uI6riw66+4";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['8'] = "7LCM656E";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['9'] = "7IyN64WE";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['10'] = "7IyN64aI";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['11'] = "67mZ7Iug";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['12'] = "7KKG6rmM";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['13'] = "64uI6riw66+4";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['14'] = "7KKG6rCZ7J2A6rKM";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['15'] = "7J6h64aI";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['16'] = "67K87JeJ7Iug";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['17'] = "67CU67O07IOI64G8";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['18'] = "7JS57IOI64G8";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['19'] = "7JSo67Cc";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['20'] = "7JSo7YyU";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['21'] = "7Iuc67KM";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['22'] = "7JSo67KM";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['23'] = "65ag6re4656E";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['24'] = "7KKG67Cl";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['25'] = "7LaU7LKc7J24";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['26'] = "7LaU7LKcaWQ=";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['27'] = "7LaU7LKc7JWE7J2065SU";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['28'] = "7LaUL+yynC/snbg=";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['29'] = "7ImQ7J20";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['30'] = "65Ox7Iug";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['31'] = "7Iu46rCA7KeA";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['32'] = "66+47Lmc64aI";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['33'] = "66+47Lmc64SY";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['34'] = "7LCM656E";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['35'] = "7KO97Iq164uI64uk";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['36'] = "7JWE64uY65Ok7JWE";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['37'] = "7JSo67C464SY";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['38'] = "c2V4";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['39'] = "7IS57Iqk";
    $_DEFENSE_POLICY['POLICY']['WORD']['LIST']['40'] = "67CU7Lm06528";
    $_DEFENSE_POLICY['POLICY']['TAG']['BOOL'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['TAG']['LIST']['0'] = "PGlmcmFtZVtbOnNwYWNlOl1dKg==";
    $_DEFENSE_POLICY['POLICY']['TAG']['LIST']['1'] = "PG1ldGFbWzpzcGFjZTpdXSo=";
    //$_DEFENSE_POLICY['POLICY']['TAG']['LIST']['2'] = "XC5cLi8=";
    //$_DEFENSE_POLICY['POLICY']['TAG']['LIST']['3'] = "XC5cLlxc";
    $_DEFENSE_POLICY['POLICY']['IP']['BOOL'] = "RkFMU0U=";
    $_DEFENSE_POLICY['POLICY']['IP']['ALLOW'] = "RkFMU0U=";
    $_DEFENSE_POLICY['POLICY']['IP']['DENY'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['FILENAME']['BOOL'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['FILENAME']['ALLOW'] = "RkFMU0U=";
    $_DEFENSE_POLICY['POLICY']['FILENAME']['DENY'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['FILENAME']['LIST']['0'] = "cGhw";
    $_DEFENSE_POLICY['POLICY']['FILENAME']['LIST']['1'] = "aHRtbA==";
    $_DEFENSE_POLICY['POLICY']['FILENAME']['LIST']['2'] = "cGh0bWw=";
    $_DEFENSE_POLICY['POLICY']['FILENAME']['LIST']['3'] = "aW5j";
    $_DEFENSE_POLICY['POLICY']['FILENAME']['LIST']['4'] = "anNw";
    $_DEFENSE_POLICY['POLICY']['FILENAME']['LIST']['5'] = "YXNw";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['BOOL'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['ALLOW'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['DENY'] = "RkFMU0U=";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['0'] = "dHh0";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['1'] = "anBn";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['2'] = "Z2lm";
    //$_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['3'] = "bXAz";   //mp3
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['3'] = "aHdw";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['4'] = "ZG9j";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['5'] = "cGRm";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['6'] = "emlw";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['7'] = "cG5n";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['8'] = "anBlZw==";
    $_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['9'] = "Ym1w";
		$_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['10'] = "eGxz";	//xls 
		$_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['11'] = "eGxzeA==";	//xlsx 
		$_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['12'] = "Y3N2";  //csv
		$_DEFENSE_POLICY['POLICY']['FILETYPE']['LIST']['13'] = "aWNv";  //ico
		
		
		    
    $_DEFENSE_POLICY['POLICY']['FILESIZE']['BOOL'] = "VFJVRQ==";
    $_DEFENSE_POLICY['POLICY']['FILESIZE']['MIN_SIZE'] = "MA==";
    $_DEFENSE_POLICY['POLICY']['FILESIZE']['MAX_SIZE'] = "MTA3Mzc0MTgyNA==";
    /* End of _DEFENSE_POLICY_PHP_ */
  }

/* End of defense_policy.php */
?>