<?

$r_column = array(
	"goodsno"					=> _("상품번호"),
	"img1"						=> _("이미지경로1"),
	"img2"						=> _("이미지경로2"),
	"img3"						=> _("이미지경로3"),
	"img4"						=> _("이미지경로4"),
	"img5"						=> _("이미지경로5"),
	"listimg"					=> _("리스트이미지"),
	"desc"						=> _("상세설명HTML"),
	"catnm1"					=> _("1차분류명"),
	"catnm2"					=> _("2차분류명"),
	"catnm3"					=> _("3차분류명"),
	"catnm4"					=> _("4차분류명"),
	"business"					=> _("노출기업그룹"),
	"goodsnm"					=> _("상품명"),
	"brandnm"					=> _("브랜드"),
	"origin"					=> _("원산지"),
	"leadtime"					=> _("제작기간"),
	"csummary"					=> _("간략설명"),
	"csearch_word"				=> _("상품검색어"),
	"cmatch_goodsnm"			=> _("매칭상품명"),
	"cetc1"						=> _("상품특이사항1"),
	"cetc2"						=> _("상품특이사항2"),
	"cetc3"						=> _("상품특이사항3"),
	"privatecid"				=> _("전용몰설정"),
	"adminmemo"					=> _("관리자메모"),
	"podsno"					=> _("PODs편집코드"),
	"podskindstr"				=> _("PODs편집명칭"),
	"statestr"					=> _("판매여부"),
	"usestock"					=> _("재고연동"),
	"shiptypestr"				=> _("배송비구분"),
	"shipprice"					=> _("개별배송비"),
	"oshipprice"				=> _("배송비원가"),
	"cost"						=> _("원가"),
	"supply"					=> _("공급가"),
	"cprice"					=> _("시중가"),
	"price"						=> _("판매가"),
	"addpage_cost"				=> _("페이지추가가격/원가"),
	"addpage_supply"			=> _("페이지추가가격/공급가"),
	"addpage_price"				=> _("페이지추가가격/판매가"),
	"totstock"					=> _("총재고"),
	"useopt"					=> _("옵션사용유무"),
	"optnm1"					=> _("1차옵션명칭"),
	"optnm2"					=> _("2차옵션명칭"),
	"opt1"						=> _("1차옵션"),
	"opt2"						=> _("2차옵션"),
	"opt_podsno"				=> _("편집코드"),
	"opt_podoptno"				=> _("편집옵션코드"),
	"opt_cost"					=> _("옵션추가원가"),
	"opt_supply"				=> _("옵션추가공급가"),
	"opt_price"					=> _("옵션추가판매가"),
	"opt_stock"					=> _("옵션재고"),
	"opt_view"					=> _("옵션노출여부"),
	"printoptnm"				=> _("인화옵션명"),
	"print_size"				=> _("인화옵션크기"),
	"printopt_cost"				=> _("인화옵션원가"),
	"printopt_supply"			=> _("인화옵션공급가"),
	"printopt_price"			=> _("인화옵션판매가"),
	"addopt_bundle_name"		=> _("추가옵션묶음명"),
	"addopt_bundle_required"	=> _("추가옵션필수여부"),
	"addopt_bundle_view"		=> _("추가옵션묶음노출여부"),
	"addoptnm"					=> _("추가옵션명"),
	"addopt_cost"				=> _("추가옵션원가"),
	"addopt_supply"				=> _("추가옵션공급가"),
	"addopt_price"				=> _("추가옵션판매가"),
	"addopt_view"				=> _("추가옵션노출여부"),
);

$r_rowspan[goodsno] = array(
	"goodsno",
	"img1",
	"img2",
	"img3",
	"img4",
	"img5",
	"listimg",
	"desc",
	"catnm1",
	"catnm2",
	"catnm3",
	"catnm4",
	"business",
	"nicknm",
	"goodsnm",
	"brandnm",
	"origin",
	"leadtime",
	"privatecid",
	"adminmemo",
	"podsno",
	"podskindstr",
	"statestr",
	"usestock",
	"shiptypestr",
	"shipprice",
	"oshipprice",
	"cost",
	"supply",
	"cprice",
	"price",
	"addpage_cost",
	"addpage_supply",
	"addpage_price",
	"totstock",
	"useopt",
	"optnm1",
	"optnm2",
	"csummary",
	"csearch_word",
	"cmatch_goodsnm",
	"cetc1",
	"cetc2",
	"cetc3",
);

$r_rowspan[addopt_bundle_no] = array(
	"addopt_bundle_name",
	"addopt_bundle_required",
	"addopt_bundle_view",	
);

$r_num_flds = array(
	"shipprice",
	"oshipprice",
	"addpage_cost",
	"addpage_supply",
	"addpage_price",
	"totstock",
	"opt_cost",
	"opt_supply",
	"opt_price",
	"opt_stock",
	"printopt_cost",
	"printopt_supply",
	"printopt_price",
	"addopt_cost",
	"addopt_supply",
	"addopt_price",
	"cost",
	"supply",
	"cprice",
	"price",
);


?>