<?
$r_column = array(
	"mid"            => _("회원아이디"),
	"grpno"          => _("그룹"),
	"state"	         => _("분류"),
	"bid"		     => _("기업그룹"),
	"name"           => _("이름(한글)"),
	"address"        => _("주소(한글)"),
	"address_sub"    => _("상세주소(한글)"),
	"phone"		     => _("전화번호(내선)"),
	"mobile"		 => _("핸드폰"),
	"apply_sms"	     => _("sms수신여부"),
	"email"		     => _("이메일"),
	"apply_email"    => _("메일수신여부"),
	"emoney"		 => _("적립금"),
	"buying"		 => _("구매금액"),
	"regdt"		     => _("가입일"),
	"memo"		     => _("관리자메모"),
	"manager_no"     => _("지사"),
	"cust_name"	     => _("사업자명"),
	"cust_type"	     => _("업태"),
	"cust_class"     => _("업종"),
	"cust_no"	     => _("사업자등록번호"),
	"cust_ceo"	     => _("대표자명"),
	"cust_ceo_phone" => _("대표자연락처"),	
	"lastlogin"      => _("최근로그인시간"),
	);
?>