<?

$r_column = array(
	"rid"					=> _("공급사아이디"),
	"rid_compnm"			=> _("공급사회사명"),
	"payno"					=> _("결제번호"),
	"ordno"					=> _("주문번호"),
	"ordseq"				=> _("주문아이템번호"),
	//"kind"				=> "구분코드",
	//"kindstr"				=> "구분명",
	//"dt"					=> "발생일",
	"orddt"					=> _("주문일"),
	"paydt"					=> _("입금/승인일"),
	"goodsno"				=> _("상품코드"),
	"goodsnm"				=> _("상품명칭"),
	"cmatch_goodsnm"		=> _("매칭상품명"),
	"podskind"				=> _("편집기코드"),
	"opt1"					=> _("상품1차옵션"),
	"opt2"					=> _("상품2차옵션"),
	"addopt_str"			=> _("추가옵션"),
	"printopt_str"			=> _("인화옵션"),
	"addpage"				=> _("추가페이지수"),
	"ea"					=> _("수량"),
	"supply_goods"			=> _("상품공급가"),
	//"price_goods"			=> "상품판매가",
	"goods_price"			=> _("상품판매가"),
	"supply_opt"			=> _("상품옵션공급가"),
	//"price_opt"			=> "상품옵션판매가",
	"aprice"				=> _("상품옵션판매가"),
	"supply_addopt"			=> _("추가옵션공급가"),
	//"price_addopt"		=> "추가옵션판매가",
	"addopt_aprice"			=> _("추가옵션판매가"),
	"supply_printopt"		=> _("인화공급가"),
	//"price_printopt"		=> "인화판매가",
	"print_aprice"			=> _("인화판매가"),
	"supply_addpage"		=> _("추가페이지공급가"),
	//"price_addpage"		=> "추가페이지판매가",
	"addpage_aprice"		=> _("추가페이지판매가"),
	/*"supply_ship"			=> "배송비공급가",
	"price_ship"			=> "배송비판매가",*/
	"shipprice"				=> _("배송비공급가"),
	"shipprice"				=> _("배송비판매가"),
	"supply"				=> _("공급가총액"),
	"price"					=> _("판매가총액"),
	"paymethod"				=> _("결제수단"),
	//"state"				=> "정산서생성여부",
	"mid"					=> _("주문자아이디"),
	"manager_name"			=> _("정산담당자명"),
	"manager_email"			=> _("정산담당자이메일"),
	"manager_phone"			=> _("정산담당자연락처"),
	"manager_mobile"		=> _("정산담당자휴대폰"),
	"manager_dep"			=> _("정산담당부서명"),
	"cust_name"				=> _("사업자명"),
	"cust_type"				=> _("거래처업태"),
	"cust_class"			=> _("거래처업종"),
	"cust_tax_type"			=> _("사업자등록유형"),
	"cust_no"				=> _("사업자등록번호"),
	"cust_ceo"				=> _("대표자명"),
	"cust_ceo_phone"		=> _("대표자연락처"),
	"cust_zipcode"			=> _("사업장우편번호"),
	"cust_address"			=> _("사업장주소"),
	"cust_address_en"		=> _("사업장영문주소"),
	"cust_phone"			=> _("사업장전화번호"),
	"cust_fax"				=> _("사업장팩스번호"),
	"cust_bank_name"		=> _("주거래은행"),
	"cust_bank_no"			=> _("주거래계좌번호"),
	"cust_bank_owner"		=> _("주거래계좌예금주"),
	"etc1"					=> _("추가정보1"),
	"etc2"					=> _("추가정보2"),
	"etc3"					=> _("추가정보3"),
	"etc4"					=> _("추가정보4"),
	"etc5"					=> _("추가정보5"),
	"b2b_goodsno 상품코드"  => _("제휴사 상품코드"),
    "csummary"              => _("간략설명"),
    "csearch_word"          => _("상품검색어"),
    "cresolution"           => _("권장해상도"),
    "cgoods_size"           => _("상품사이즈"),
    "cetc1"                 => _("상품특이사항1"),
    "cetc2"                 => _("상품특이사항2"),
    "cetc3"                 => _("상품특이사항3")
);

$r_num_flds = array(
	"addpage",
	"ea",
	"supply_goods",
	"goods_price",
	"supply_opt",
	"aprice",
	"supply_addopt",
	"addopt_aprice",
	"supply_printopt",
	"print_aprice",
	"supply_addpage",
	"addpage_aprice",
	"shipprice",
	"shipprice",
	"supply",
	"price",
);

?>